/**
 * setup_app_icons.js
 * Resizes and copies role-specific app icons into all mipmap density folders.
 * Run: node setup_app_icons.js
 */
import sharp from "sharp";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const androidResDir = path.resolve(__dirname, "android/app/src/main/res");

// mipmap folder → required icon size (px)
const MIPMAP_SIZES = {
  "mipmap-mdpi":    48,
  "mipmap-hdpi":    72,
  "mipmap-xhdpi":   96,
  "mipmap-xxhdpi":  144,
  "mipmap-xxxhdpi": 192,
};

// Source icons (generated by generate_image tool — stored in user AppData)
const ICON_SOURCES = {
  farmer:   "C:/Users/KELOTHU SHARATH/.gemini/antigravity-ide/brain/479fb086-b663-4bc7-b919-8af7dfbf1045/farmer_app_icon_1786204818575.png",
  provider: "C:/Users/KELOTHU SHARATH/.gemini/antigravity-ide/brain/479fb086-b663-4bc7-b919-8af7dfbf1045/provider_app_icon_1786204837098.png",
  admin:    "C:/Users/KELOTHU SHARATH/.gemini/antigravity-ide/brain/479fb086-b663-4bc7-b919-8af7dfbf1045/admin_app_icon_1786204855904.png",
};

// Also copy to assets/icons/ directory for organized storage
const ASSET_OUTPUT_DIR = path.resolve(__dirname, "assets/icons");

async function copyIconsForRole(role) {
  const srcIcon = ICON_SOURCES[role];
  if (!fs.existsSync(srcIcon)) {
    console.error(`❌ Source icon not found for ${role}: ${srcIcon}`);
    return;
  }

  // Save to assets/icons/{role}/ at full size
  const assetDir = path.join(ASSET_OUTPUT_DIR, role);
  fs.mkdirSync(assetDir, { recursive: true });
  await sharp(srcIcon).resize(1024, 1024).png().toFile(path.join(assetDir, "ic_launcher_source.png"));
  console.log(`✅ Saved source icon for ${role}`);

  // Copy resized icons to each mipmap density folder
  for (const [mipmapFolder, size] of Object.entries(MIPMAP_SIZES)) {
    const targetDir = path.join(androidResDir, mipmapFolder);
    if (!fs.existsSync(targetDir)) {
      fs.mkdirSync(targetDir, { recursive: true });
    }

    // ic_launcher.png (standard square icon)
    await sharp(srcIcon)
      .resize(size, size, { fit: "contain", background: { r: 255, g: 255, b: 255, alpha: 0 } })
      .png()
      .toFile(path.join(targetDir, "ic_launcher.png"));

    // ic_launcher_round.png (circular icon)
    // Create a circular mask
    const circle = Buffer.from(
      `<svg><circle cx="${size/2}" cy="${size/2}" r="${size/2}"/></svg>`
    );
    await sharp(srcIcon)
      .resize(size, size)
      .composite([{ input: circle, blend: "dest-in" }])
      .png()
      .toFile(path.join(targetDir, "ic_launcher_round.png"));

    // ic_launcher_foreground.png (adaptive icon foreground, larger for safe zone)
    const fgSize = Math.round(size * 1.5); // 108dp equivalent
    await sharp(srcIcon)
      .resize(fgSize, fgSize, { fit: "contain", background: { r: 255, g: 255, b: 255, alpha: 0 } })
      .png()
      .toFile(path.join(targetDir, "ic_launcher_foreground.png"));
  }

  console.log(`✅ All mipmap icons updated for role: ${role}`);
}

// Export function for use in build_all_apks.js
export { copyIconsForRole };

// If run directly, copy icons for all roles
const role = process.argv[2];
if (role && ["farmer", "provider", "admin"].includes(role)) {
  console.log(`\n🎨 Setting up icons for: ${role}\n`);
  copyIconsForRole(role).then(() => console.log("Done!")).catch(console.error);
} else {
  console.log("Usage: node setup_app_icons.js <farmer|provider|admin>");
  console.log("Or import copyIconsForRole() in build_all_apks.js");
}
